# Generated by Django 4.2.25 on 2025-11-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='em_estoque',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
